### ISSUE TITLE
train/val/test split setting

### ISSUE THREAD

**Issue by HochCC** [lodurality/GEM3D_paper_code#1]
Thanks for sharing your great work, could you please share the train/val/test split file? So that I can do experiment in the same setting with you. I can't find how to split in your or 3dshape2vecset repo.

**Comment by lodurality** [comment]
Hi, you can download the data here (link from their repository; I think it should be occupancies folder). I think the problem is that each shape category has separate train/test/split files

https://drive.google.com/drive/folders/1UFPi_UklH5clWKxxeL1IsxfjdUfc7i4x

**Comment by lodurality** [comment]
I think you need occupancies folder (but the dataset is very large). 

I do plan to release our preprocessed data, but uses splits in occupancies folder.
